[build]
  command = "npm run maybe-build"
  publish = "public"

[[plugins]]
  package = "netlify-plugin-onboarding"

[template.environment]
  GITHUB_USERNAME = "Your GitHub Username (e.g. @jlengstorf)"
