[build]
  command = "npm run build"
  publish = "site/public"

[[plugins]]
  package = "../netlify-plugin-onboarding"

[template.environment]
  GITHUB_USERNAME = "Your GitHub Username (e.g. @jlengstorf)"
